### ISSUE TITLE
Why does tracer lose attachment ?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [hjr265/ptrace.go#1]
I want write a sandbox for online judge. this is my demo code:

```
    "fmt"
    "os"
    "syscall"

    "github.com/hjr265/ptrace.go/ptrace"
)



func main() {
    var rusage syscall.Rusage
    var incall = true
    proc, err := os.StartProcess("./main", []string{"main"}, &os.ProcAttr{Sys: &syscall.SysProcAttr{
        Ptrace: true},
    })
    if err != nil {
        panic(err)
    }
    tracer, err := ptrace.Attach(proc)
    if err != nil {
        panic(err)
    }
        // it seems the setlimit does not work for the main.go process
    var rlimit syscall.Rlimit
    rlimit.Cur = 1
    rlimit.Max = 2
    err = syscall.Setrlimit(syscall.RLIMIT_CPU, &rlimit)
    if err != nil {
        panic(err)
    }
    for {
        status := syscall.WaitStatus(0)
        wpid, err := syscall.Wait4(proc.Pid, &status, syscall.WSTOPPED, &rusage)
        if err != nil {
            panic(err)
        }
        fmt.Printf("USER CPU TIME %v\n", rusage.Utime)
        fmt.Printf("KERNEL CPU TIME %v\n", rusage.Stime)
        if status.Exited() {
            fmt.Println("exit")
            fmt.Println(rusage.Stime)
            break
        }
        if status.CoreDump() {
            fmt.Println("CoreDump")
        }
        if status.Continued() {
            fmt.Println("Continued")
        }
        if status.Signaled() {
            fmt.Println("signal")
            fmt.Println(status.Signal().String())
        }
        if status.Stopped() {
            fmt.Println(status.StopSignal())
            fmt.Println("stop")
        }
        regs, err := tracer.GetRegs()
        if err != nil {
            panic(err)
        }
        fmt.Println("sys call is ", regs.Orig_rax)
        if regs.Orig_rax == syscall.SYS_WRITE {
            if incall {
                incall = false

                _, err = tracer.GetRegs()
                if err != nil {
                    panic(err)
                }
                fmt.Printf("The child made a system call with, %d,%d,%d \n",regs.Rdi, regs.Rsi, regs.Rdx)
            } else {
                regs, err := tracer.GetRegs()
                if err != nil {
                    panic(err)
                }
                fmt.Printf("write returned %v\n", regs.Rax)
                fmt.Printf("call %d\n", regs.Rdi)
                incall = true
            }
        }
        //0表示不发出信号
        err = tracer.Syscall(syscall.Signal(0))
        if err != nil {
            fmt.Println(err)
        }
    }
}
```

this is my main.go

```
/*
    Author:mike
    CreatedAt:2014年05月29日 下午 02时07分58秒 CST
*/
package main

import (
    "fmt"
    "os"
    "syscall"
    "time"
)

func main() {
    var rlimit syscall.Rlimit

    rlimit.Cur = 1
    rlimit.Max = 2
    err = syscall.Setrlimit(syscall.RLIMIT_CPU, &rlimit)
    if err != nil {
        panic(err)
    }
    for i := 0; i < 1000000; i++ {
        for j := 0; i < 100000; j++ {
            for q := 0; q < 1000; q++ {

            }
        }
    }

    fmt.Println("Hello")
    f, err := os.Open("tmp")
    if err != nil {
        panic(err)
    }
    defer f.Close()
    time.Sleep(5 * time.Second)
    fmt.Println("Hello")
}
```

I hope to catch the CPU time limit signal , but always get panic: no such process at`regs.GetRegs` , It seems the main.go process doesn't exit yet, but I loss the attachment of the process. What makes it happend? 

BTW,I found no `prlimit` in the syscall package, Do you have any idea that How I can set limit to the main.go process except add `setrlimit` code in the main.go?

**Comment by hjr265** [comment]
@ggaaooppeenngg Your first question is more related to ptracing itself and how Go handles go routines. I tried adding 

``` go
runtime.LockOSThread()
defer runtime.UnlockOSThread()
```

At the very beginning of your `main()` func. And it seemed to fix the "no such process" err.

In Go, you don't have a func for `prlimit` syscall. But you can use the `Syscall6()` func along with `SYS_PRLIMIT64` to achieve the same.

``` go
_, _, errno := syscall.RawSyscall6(syscall.SYS_PRLIMIT64, uintptr(pid), syscall.RLIMIT_CPU, uintptr(unsafe.Pointer(&syscall.Rlimit{
    Cur: uint64(c.limits.Cpu)/1e9 + 1,
    Max: uint64(c.limits.Cpu)/1e9 + 1,
})), 0, 0, 0)
if errno != 0 {
    err = errno
    return err
}
```

By the way, is the online judge you are working on live anywhere yet? I faced the same issue while working on a pet-project (a sandbox, for compiling and running arbitrary code; although right now I am working on a ptrace-free sandbox for better performance). For an online judge (CodeMarshal) that I have been working on, I ended up using a Python based implementation (it will soon be replaced though by the new one though). But I am still using a ptrace-based sandbox for a "PC^2 replacement" (Cactus). Since it is meant to be redistributable and easy to use. The second code snippet above has been taken straight from Cactus.

**Comment by ggaaooppeenngg** [comment]
It's very inspiring . The online judge is just a pet-project too, not live. I want to combine it with docker so that I do not need to worry about bad system call. Could I get more information about the Python based implementation?

**Comment by hjr265** [comment]
Docker is a really cool idea! :smile:

The new sandbox that I am writing in Go actually uses the same techniques that Docker uses. I could have directly used Docker, but I am actually trying to learn about some of the nitty gritty details of Linux. Also, I am enjoying the flexibility of writing the sandbox by relying only on what the Linux system provides you. I am using clone flags, chroot, and some other stuff to design the sandbox. It's 70% done right now. I am going to make it available as an online service so that others can use it using simple api calls. I am hoping to have it ready by end of next month.

Regarding the Python based implementation. Unfortunately I cannot give out much details as it is being used in CodeMarshal. So I need to maintain a bit of discretion here. It is a chroot plus ptrace based solution. With very tight restrictions on the system calls you can make. Basically it just gives you enough ability to write algorithmic solutions to ACM-ICPC and IOI style programming contest problems. But then again, since it is written in Python and moreover it uses ptrace, it is not really very fast. At least not as fast as I want it to be. Sorry, I am not liberty to say much more here. But if you have any specific questions regarding implementing a sandbox, please let me know. I will be glad to help.

Cactus is a pet project of mine, it is a Go program that will be available as a compiled binaries sometime next month. The idea is that you can just download and run it and use it to host a programming contest like you would do with PC^2. Since I personally don't like PC^2 and some of the annoyances of that program, I am trying to "fix" or avoid all those issues in Cactus. Among a lot of things, one of the important goals is to make it "easy to use". Which includes "easy to configure" as well. For example, unlike PC^2, you don't have to worry about the Java runtime even. You just download a single binary file and run it in your terminal and you have a working contest hosting tool. And since it is web-based, you don't have to run around each computer in a network and set it up; you can just access it via the web browser.

Here are a few screenshots of Cactus in case you are interested: http://imgur.com/a/Qocbv
I am going to eventually make this open source. But may be not as soon as I release the first version.

**Comment by ggaaooppeenngg** [comment]
That's cool!~ I am expecting !
